[package]
name = "peace-frontend"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
peace-backend = {path = "../backend"}
lazy_static = "*"
libloading = "0.5.0"
capstone = "0.5.0"
faerie = "0.6.0"
target-lexicon = "0.2.0"