[package]
name = "peace"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
peace-backend = {path = "backend"}
peace-frontend = {path = "frontend"}