[package]
name = "peak-compiler"
version = "0.1.0"
authors = ["adelprokurov"]
edition = "2018"

[dependencies]
libc = "0.2.47"
byteorder = "1.2.7"
capstone = "0.5.0"
fnv = "1.0.6"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winbase", "memoryapi"] }
