[package]
name = "peace-backend"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
winapi = "0.3.6"
kernel32-sys = "0.2.2"
byteorder = "1.2.7"
capstone = "0.5.0"