[package]
name = "tiny-compiler"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
peace = {path = "../"}
itertools = "*"
capstone = "0.5.0"
structopt = "0.2.14"